@startuml
skinparam svgDimensionStyle false
hide footbox

title "mXDE Process Flow: externally visible transactions"
box "Grouped Client"
participant "QEDm\nClinical Data Client" as qClient
participant "mXDE\nClinical Data Client" as pClient
participant "Document Sharing\nContent Consumer" as dClient
end box
box "Grouped Server"
participant "QEDm\nClinical Data Source" as qServer
participant "mXDE\nData Element Extractor" as extractor
participant "Document Sharing\nInfrastructure" as dServer
end box

activate qClient
qClient ->o qServer : PCC-44
activate qServer
return 
deactivate qServer

activate dClient
dClient ->o dServer : PCC-1 (e.g. XDS, XCA, MHD)
activate dServer
return 
deactivate dServer
deactivate dClient

deactivate qClient 

@enduml
