# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.mxde
canonical: https://profiles.ihe.net/ITI/mXDE
version: 1.3.0
name: IHE_ITI_mXDE
title: "Mobile Cross-Enterprise Document Data Element Extraction (mXDE)"
description: The Mobile Cross-Enterprise Document Data Element Extraction (mXDE) Profile provides the means to access data elements extracted from shared structured documents. The profile enables the deployment of health data exchange infrastructures where fine-grained access to health data coexists and complements the sharing of coarse-grained documents and the fine-grained data elements they contain.
releaseLabel: ci-build
#releaseLabel: Public Comment
#date: 2023-xx-xx
status: draft
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: mXDE Home
    generation: markdown
  volume-1.md:
    title: 1:45 Mobile Cross-Enterprise Document Data Element Extraction (mXDE)
    generation: markdown
  ITI-43.md:
    title: 2:3.43 Retrieve Document Set [ITI-43]
    generation: markdown
  testplan.md:
    title: Test Plan
    generation: markdown
  issues.md:
    title: Open and Closed Issues
    generation: markdown
  other.md:
    title: Changes to Other Documents
    generation: markdown
    
menu:
  mXDE Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
    Deployment Models: volume-1.html#deployment-models
  Volume 2:
    "Retrieve Document Set [ITI-43]": ITI-43.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
  Other: other.html
