# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.mxde
canonical: https://profiles.ihe.net/ITI/mXDE
version: 1.3.0-current
name: IHE_ITI_mXDE
title: "Mobile Cross-Enterprise Document Data Element Extraction (mXDE)"
description: The Mobile Cross-Enterprise Document Data Element Extraction (mXDE) Profile provides the means to access data elements extracted from shared structured documents. The profile enables the deployment of health data exchange infrastructures where fine-grained access to health data coexists and complements the sharing of coarse-grained documents and the fine-grained data elements they contain.
releaseLabel: ci-build
#releaseLabel: Public Comment
#date: 2023-xx-xx
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+

dependencies:
  ihe.iti.mhd: 
    id: iheitimhd
    uri: https://profiles.ihe.net/ITI/MHD/ImplementationGuide/ihe.iti.mhd
    version: 4.2.0
  ihe.iti.pdqm: 
    id: ihepdqm
    uri: https://profiles.ihe.net/ITI/PDQm/ImplementationGuide/ihe.iti.pdqm
    version: 2.4.0
  ihe.iti.pixm:
    id: iheitipixm
    uri: https://profiles.ihe.net/ITI/PIXm/ImplementationGuide/ihe.iti.pixm
    version: 3.0.2
  ihe.iti.mcsd:
    id: iheitimcsd
    uri: https://profiles.ihe.net/ITI/mCSD/ImplementationGuide/ihe.iti.mcsd
    version: 3.8.0
  ihe.formatcode.fhir:
    id: iheformatcodefhir
    uri: https://profiles.ihe.net/fhir/ihe.formatcode.fhir/ImplementationGuide/ihe.formatcode.fhir
    version: 1.1.0
  ihe.iti.balp:
    id: iheitibasicaudit
    uri: https://profiles.ihe.net/ITI/BALP/ImplementationGuide/ihe.iti.balp
    version: 1.1.1
  ihe.iti.pmir:
    id: iheitipmir
    uri: https://profiles.ihe.net/ITI/PMIR/ImplementationGuide/ihe.iti.pmir
    version: 1.5.0
  ihe.iti.svcm:
    id: iheitisvcm
    uri: https://profiles.ihe.net/ITI/SVCM/ImplementationGuide/ihe.iti.svcm
    version: 1.5.0



parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: Mobile Cross-Enterprise Document Data Element Extraction (mXDE)
    generation: markdown
  volume-1.md:
    title: 1:45 Mobile Cross-Enterprise Document Data Element Extraction (mXDE)
    generation: markdown
  ITI-43.md:
    title: 2:3.43 Retrieve Document Set [ITI-43]
    generation: markdown
  testplan.md:
    title: Test Plan
    generation: markdown
  issues.md:
    title: Significant Changes & Issues
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  downloads.md:
    title: Downloads and Analysis
    generation: markdown
    
menu:
  mXDE Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#1451-mxde-actors-transactions-and-content-modules
    Actor Options: volume-1.html#1452-mxde-actor-options
    Required Actor Groupings: volume-1.html#1453-mxde-required-actor-groupings
    Overview: volume-1.html#1454-mxde-overview
    Security Considerations: volume-1.html#1455-mxde-security-considerations
    Cross-Profile Considerations: volume-1.html#1456-mxde-cross-profile-considerations
    Deployment Models: volume-1.html#1457-deployment-models
  Volume 2:
    "Retrieve Document Set [ITI-43]": ITI-43.html
  Artifacts: artifacts.html
  Other:
    Test Plan: testplan.html
    Changes to Other IHE Specifications: other.html
    Downloads and Analysis: downloads.html
    
